const COLOR = {
  COMPLETED_TODO_FONT: `#D4D4D4`,
  BACKGROUND: 'rgb(230,230,230)',
  TODO_FORM_BACKGROUND: '#FFFFFF',
  CARD_BACKGROUND: '#FFFFFF',
  CARD_BORDER: '#DDDDDD',
  INPUT_BOX_BACKGROUND: '#F0F1F2',
};

export { COLOR };
